version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  mac:
    macos:
      xcode: 10.1.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: Download canary beta
          command: |
            curl -O https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-76.0.151.0.pkg  
      - cypress/run:
          name: Install canary beta
          command: |
            sudo installer -pkg MicrosoftEdgeCanary-76.0.151.0.pkg -target /  
      - cypress/run:
          name: Get cypress-edge package
          command: |
            curl -O https://github.com/YOU54F/cypress/releases/download/v3.2.0-edge.1/cypress-3.2.0-edge.1.zip
      - cypress/run:
          name: export env var
          command: |
            export CYPRESS_INSTALL_BINARY=https://github.com/YOU54F/cypress/releases/download/v3.2.0-edge.1/cypress-3.2.0-edge.1.zip  
      - cypress/run:
          name: install cypress
          command: |
            npm install @you54f/cypress --save  
      - cypress/run:
          name: run cypress
          command: |
            node_modules/.bin/cypress run --browser edge 
